default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: '123456'
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_app_development

test:
  <<: *default
  database: react_app_test

production:
  <<: *default
  database: react_app_production
  username: react_app
  password: <%= ENV['REACT_APP_DATABASE_PASSWORD'] %>
